### ISSUE TITLE
An icon shows up while typing input on Windows Edge

### ISSUE THREAD

**Issue by montomos** [rakuten-rex/password#10]
@Kosukeee 
An icon shows up while typing input on Windows Edge.

<img width="957" alt="スクリーンショット 2020-06-09 10 38 23" src="https://user-images.githubusercontent.com/1501667/84096777-b71bc980-aa3d-11ea-9071-1aabf512e9e2.png">

**Comment by Kosukeee** [comment]
@montomos -san,
Fixed the issue and released v.1.2.1.
